server:
  port: 8000
spring:
  application:
    name: spring-boot-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#  security:
#    user:
#      password: 123456
#      name: admin